name: Rescan Application in CAST Imaging Console

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  rescan:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: C:\Users\JKM\Documents\Cast_Software\G\SOURCES\JKM_Shopizer

      - name: List directory contents of repository
        shell: cmd
        run: dir "C:\Users\JKM\Documents\Cast_Software\G\SOURCES\JKM_Shopizer"

      - name: Set JAVA_HOME environment variable
        shell: cmd
        run: |
          set JAVA_HOME="C:\Program Files\Java\jdk-11.0.15.1"
          echo JAVA_HOME is set to %JAVA_HOME%

      - name: Verify Java Version
        shell: cmd
        run: |
          "%JAVA_HOME%\bin\java.exe" -version

      - name: Rescan Application
        run: |
          java -jar aip-console-tools-cli.jar add --apikey="864h5khS.MbjJHcFQL13M71VdR70XT3KoPJguDW9u" -n "JKM_Shopizer" --server-url="http://localhost:8081" --no-clone -f "C:\Users\JKM\Documents\Cast_Software\G\SOURCES\JKM_Shopizer" --verbose=false --set-as-current=true --upload-application=true --process-imaging=true
